import type { PluginSpec, ProjectOptions, SpecFile } from '@/lib/types';

export function generatePluginYml(spec: PluginSpec): string {
  const commands = spec.commands.map((c) => {
    const aliases = c.aliases.length > 0
      ? `\n    aliases: [${c.aliases.map((a) => `'${a}'`).join(', ')}]`
      : '';
    return `  ${c.name}:
    description: ${c.description}
    usage: ${c.usage}
    permission: ${c.permission}${aliases}`;
  }).join('\n');

  const permissions = spec.permissions.map((p) => {
    return `  ${p.name}:
    description: ${p.description}
    default: ${p.default}`;
  }).join('\n');

  const deps = spec.dependencies.length > 0
    ? `depend: [${spec.dependencies.map((d) => d.name).join(', ')}]`
    : '';

  const softDeps = spec.dependencies.filter((d) => d.optional);
  const softDepLine = softDeps.length > 0
    ? `softdepend: [${softDeps.map((d) => d.name).join(', ')}]`
    : '';

  return `name: ${spec.name}
version: ${spec.version}
main: ${spec.packageName}.${spec.mainClass}
api-version: '${spec.apiVersion}'
author: ${spec.author}
description: ${spec.description}
${deps}
${softDepLine}
commands:
${commands}

permissions:
${permissions}
`;
}

export function generateConfigYml(spec: PluginSpec): string {
  const configLines = spec.configKeys.map((k) => {
    return `# ${k.comment}
${k.key}: ${k.value}`;
  }).join('\n');

  const messageKeys = spec.commands.map((c) => {
    return `# Message shown when ${c.name} command is used
messages.${c.name}: "&a${c.description}"`;
  }).join('\n');

  return `# ${spec.name} Configuration
# Generated by NOVX AI
# 
# Color codes: &a=green &b=aqua &c=red &e=yellow &f=white &6=gold
# &l=bold &o=italic &r=reset

# General Settings
${configLines}

# Messages
${messageKeys}

# Message shown when player lacks permission
messages.no-permission: "&cYou do not have permission to use this command."

# Message shown when console tries a player-only command
messages.player-only: "&cThis command can only be used by players."
`;
}

export function generatePomXml(spec: PluginSpec, options: ProjectOptions): string {
  const deps = spec.dependencies.map((d) => {
    return `    <dependency>
      <groupId>${d.groupId}</groupId>
      <artifactId>${d.artifactId}</artifactId>
      <version>${d.version}</version>
      <scope>provided</scope>${d.optional ? '\n      <optional>true</optional>' : ''}
    </dependency>`;
  }).join('\n');

  const hasPlaceholderAPI = spec.dependencies.some((d) => d.name === 'PlaceholderAPI');
  const hasVault = spec.dependencies.some((d) => d.name === 'Vault');

  let repos = `    <repository>
      <id>papermc</id>
      <url>https://repo.papermc.io/repository/maven-public/</url>
    </repository>`;

  if (hasPlaceholderAPI) {
    repos += `\n    <repository>
      <id>placeholderapi</id>
      <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
    </repository>`;
  }
  if (hasVault) {
    repos += `\n    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>`;
  }

  return `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>${spec.packageName}</groupId>
  <artifactId>${spec.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}</artifactId>
  <version>${spec.version}</version>
  <packaging>jar</packaging>

  <properties>
    <maven.compiler.source>${options.javaVersion}</maven.compiler.source>
    <maven.compiler.target>${options.javaVersion}</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <repositories>
${repos}
  </repositories>

  <dependencies>
    <dependency>
      <groupId>io.papermc.paper</groupId>
      <artifactId>paper-api</artifactId>
      <version>${options.mcVersion}-R0.1-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
${deps}
  </dependencies>

  <build>
    <finalName>\${project.artifactId}-\${project.version}</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
        <configuration>
          <source>${options.javaVersion}</source>
          <target>${options.javaVersion}</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
`;
}

export function generateMainClass(spec: PluginSpec, _options: ProjectOptions): string {
  const pkg = spec.packageName;
  const className = spec.mainClass;
  const pkgPath = pkg.replace(/\./g, '/');

  const commandRegistrations = spec.commands.map((c) => {
    const cmdClass = c.name.charAt(0).toUpperCase() + c.name.slice(1) + 'Command';
    return `        getCommand("${c.name}").setExecutor(new ${cmdClass}(this));`;
  }).join('\n');

  const listenerRegistrations = spec.listeners.map((l) => {
    const listenerClass = l.event.replace('Event', 'Listener');
    return `        pm.registerEvents(new ${listenerClass}(this), this);`;
  }).join('\n');

  const hasListeners = spec.listeners.length > 0;
  const hasCommands = spec.commands.length > 0;

  const imports = [
    `import ${pkg}.managers.ConfigManager;`,
    `import ${pkg}.managers.MessageManager;`,
  ];
  if (hasCommands) {
    spec.commands.forEach((c) => {
      const cmdClass = c.name.charAt(0).toUpperCase() + c.name.slice(1) + 'Command';
      imports.push(`import ${pkg}.commands.${cmdClass};`);
    });
  }
  if (hasListeners) {
    spec.listeners.forEach((l) => {
      const listenerClass = l.event.replace('Event', 'Listener');
      imports.push(`import ${pkg}.listeners.${listenerClass};`);
    });
  }

  return `package ${pkg};

import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.plugin.PluginManager;
${imports.join('\n')}

/**
 * ${spec.name} - ${spec.description}
 *
 * Main plugin class. Entry point for the plugin lifecycle.
 *
 * @author ${spec.author}
 * @version ${spec.version}
 */
public class ${className} extends JavaPlugin {

    private ConfigManager configManager;
    private MessageManager messageManager;

    @Override
    public void onEnable() {
        // Save default config if it doesn't exist
        saveDefaultConfig();

        // Initialize managers
        this.configManager = new ConfigManager(this);
        this.messageManager = new MessageManager(this);

        // Register commands
${hasCommands ? commandRegistrations : '        // No commands registered'}

        // Register event listeners
${hasListeners ? '        PluginManager pm = getServer().getPluginManager();\n' + listenerRegistrations : '        // No listeners registered'}

        getLogger().info("${spec.name} v${spec.version} has been enabled!");
    }

    @Override
    public void onDisable() {
        // Cleanup resources
        getLogger().info("${spec.name} has been disabled!");
    }

    /**
     * Get the config manager instance.
     * @return ConfigManager instance
     */
    public ConfigManager getConfigManager() {
        return configManager;
    }

    /**
     * Get the message manager instance.
     * @return MessageManager instance
     */
    public MessageManager getMessageManager() {
        return messageManager;
    }
}
`;
}

export function generateCommandClass(
  spec: PluginSpec,
  commandName: string,
  _options: ProjectOptions
): string {
  const pkg = spec.packageName;
  const cmd = spec.commands.find((c) => c.name === commandName);
  if (!cmd) return '';

  const className = cmd.name.charAt(0).toUpperCase() + cmd.name.slice(1) + 'Command';
  const mainClass = spec.mainClass;

  return `package ${pkg}.commands;

import ${pkg}.${mainClass};
import ${pkg}.managers.MessageManager;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;

/**
 * Command handler for /${cmd.name}
 * ${cmd.description}
 *
 * Permission: ${cmd.permission}
 * Usage: ${cmd.usage}
 */
public class ${className} implements CommandExecutor {

    private final ${mainClass} plugin;
    private final MessageManager messages;

    public ${className}(${mainClass} plugin) {
        this.plugin = plugin;
        this.messages = plugin.getMessageManager();
    }

    @Override
    public boolean onCommand(@NotNull CommandSender sender, @NotNull Command command, @NotNull String label, @NotNull String[] args) {
        // Permission check
        if (!sender.hasPermission("${cmd.permission}")) {
            messages.send(sender, "no-permission");
            return true;
        }

        // Player-only check (uncomment if needed)
        // if (!(sender instanceof Player player)) {
        //     messages.send(sender, "player-only");
        //     return true;
        // }

        // TODO: Implement ${cmd.name} command logic
        messages.send(sender, "${cmd.name}");
        return true;
    }
}
`;
}

export function generateListenerClass(
  spec: PluginSpec,
  eventName: string,
  _options: ProjectOptions
): string {
  const pkg = spec.packageName;
  const listener = spec.listeners.find((l) => l.event === eventName);
  if (!listener) return '';

  const className = eventName.replace('Event', 'Listener');
  const mainClass = spec.mainClass;
  const eventPkg = eventName.startsWith('Player') ? 'org.bukkit.event.player' : 'org.bukkit.event';
  const entityClass = eventName.replace('Event', '');

  return `package ${pkg}.listeners;

import ${pkg}.${mainClass};
import ${pkg}.managers.MessageManager;
import ${eventPkg}.${eventName};
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.jetbrains.annotations.NotNull;

/**
 * Listener for ${eventName}
 * ${listener.description}
 */
public class ${className} implements Listener {

    private final ${mainClass} plugin;
    private final MessageManager messages;

    public ${className}(${mainClass} plugin) {
        this.plugin = plugin;
        this.messages = plugin.getMessageManager();
    }

    @EventHandler
    public void on${entityClass}(@NotNull ${eventName} event) {
        // TODO: Implement ${listener.description}
        plugin.getLogger().info("${eventName} triggered");
    }
}
`;
}

export function generateConfigManager(spec: PluginSpec, _options: ProjectOptions): string {
  const pkg = spec.packageName;
  const mainClass = spec.mainClass;

  return `package ${pkg}.managers;

import ${pkg}.${mainClass};
import org.bukkit.configuration.file.FileConfiguration;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Manages plugin configuration access.
 * Provides typed getters for config values with defaults.
 */
public class ConfigManager {

    private final ${mainClass} plugin;
    private FileConfiguration config;

    public ConfigManager(${mainClass} plugin) {
        this.plugin = plugin;
        this.config = plugin.getConfig();
    }

    /**
     * Reload configuration from disk.
     */
    public void reload() {
        plugin.reloadConfig();
        this.config = plugin.getConfig();
    }

    /**
     * Get a string value from config.
     * @param path The config path
     * @param def The default value
     * @return The config value or default
     */
    public String getString(@NotNull String path, @Nullable String def) {
        return config.getString(path, def);
    }

    /**
     * Get a string value from config.
     * @param path The config path
     * @return The config value or empty string
     */
    public String getString(@NotNull String path) {
        return config.getString(path, "");
    }

    /**
     * Get an integer value from config.
     * @param path The config path
     * @param def The default value
     * @return The config value or default
     */
    public int getInt(@NotNull String path, int def) {
        return config.getInt(path, def);
    }

    /**
     * Get a boolean value from config.
     * @param path The config path
     * @param def The default value
     * @return The config value or default
     */
    public boolean getBoolean(@NotNull String path, boolean def) {
        return config.getBoolean(path, def);
    }

    /**
     * Get a double value from config.
     * @param path The config path
     * @param def The default value
     * @return The config value or default
     */
    public double getDouble(@NotNull String path, double def) {
        return config.getDouble(path, def);
    }
}
`;
}

export function generateMessageManager(spec: PluginSpec, _options: ProjectOptions): string {
  const pkg = spec.packageName;
  const mainClass = spec.mainClass;

  return `package ${pkg}.managers;

import ${pkg}.${mainClass};
import org.bukkit.ChatColor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.jetbrains.annotations.NotNull;

/**
 * Manages plugin messages.
 * Reads message templates from config and applies color codes.
 */
public class MessageManager {

    private final ${mainClass} plugin;

    public MessageManager(${mainClass} plugin) {
        this.plugin = plugin;
    }

    /**
     * Send a message from config to a command sender.
     * @param sender The command sender (player or console)
     * @param key The config key for the message
     */
    public void send(@NotNull CommandSender sender, @NotNull String key) {
        String message = plugin.getConfig().getString("messages." + key, "");
        if (message.isEmpty()) {
            return;
        }
        sender.sendMessage(colorize(message));
    }

    /**
     * Send a raw message with color codes to a command sender.
     * @param sender The command sender
     * @param message The raw message
     */
    public void sendRaw(@NotNull CommandSender sender, @NotNull String message) {
        sender.sendMessage(colorize(message));
    }

    /**
     * Convert & color codes to ChatColor.
     * @param message The message with & codes
     * @return The colorized message
     */
    public static String colorize(@NotNull String message) {
        return ChatColor.translateAlternateColorCodes('&', message);
    }

    /**
     * Strip color codes from a message.
     * @param message The message
     * @return The plain text
     */
    public static String stripColor(@NotNull String message) {
        return ChatColor.stripColor(colorize(message));
    }
}
`;
}

export function generateReadme(spec: PluginSpec, options: ProjectOptions): string {
  const commandsList = spec.commands.map((c) =>
    `- \`/${c.name}\` - ${c.description} (Permission: \`${c.permission}\`)`
  ).join('\n');
  const permsList = spec.permissions.map((p) =>
    `- \`${p.name}\` - ${p.description} (Default: ${p.default})`
  ).join('\n');
  const depsList = spec.dependencies.length > 0
    ? spec.dependencies.map((d) => `- [${d.name}](https://www.spigotmc.org/resources/${d.name.toLowerCase()})`).join('\n')
    : 'None';

  return `# ${spec.name}

${spec.description}

## Requirements
- ${options.platform} ${options.mcVersion}
- Java ${options.javaVersion}

## Dependencies
${depsList}

## Commands
${commandsList}

## Permissions
${permsList}

## Installation
1. Download the .jar file
2. Place it in your server's \`plugins/\` folder
3. Restart your server
4. Configure in \`plugins/${spec.name}/config.yml\`

## Configuration
Edit \`config.yml\` to customize messages, values, and settings.

## Building from Source
\`\`\`bash
mvn clean package
\`\`\`
The compiled JAR will be in \`target/\`.

---

Generated by [NOVX AI](https://novx.ai)
`;
}

export function generateAllFiles(spec: PluginSpec, options: ProjectOptions): SpecFile[] {
  const files: SpecFile[] = [];
  const pkgPath = spec.packageName.replace(/\./g, '/');

  // Main class
  files.push({
    path: `src/main/java/${pkgPath}/${spec.mainClass}.java`,
    content: generateMainClass(spec, options),
    language: 'java',
  });

  // Command classes
  for (const cmd of spec.commands) {
    files.push({
      path: `src/main/java/${pkgPath}/commands/${cmd.name.charAt(0).toUpperCase() + cmd.name.slice(1)}Command.java`,
      content: generateCommandClass(spec, cmd.name, options),
      language: 'java',
    });
  }

  // Listener classes
  for (const listener of spec.listeners) {
    files.push({
      path: `src/main/java/${pkgPath}/listeners/${listener.event.replace('Event', 'Listener')}.java`,
      content: generateListenerClass(spec, listener.event, options),
      language: 'java',
    });
  }

  // Managers
  files.push({
    path: `src/main/java/${pkgPath}/managers/ConfigManager.java`,
    content: generateConfigManager(spec, options),
    language: 'java',
  });
  files.push({
    path: `src/main/java/${pkgPath}/managers/MessageManager.java`,
    content: generateMessageManager(spec, options),
    language: 'java',
  });

  // Resources
  files.push({
    path: 'src/main/resources/plugin.yml',
    content: generatePluginYml(spec),
    language: 'yaml',
  });
  files.push({
    path: 'src/main/resources/config.yml',
    content: generateConfigYml(spec),
    language: 'yaml',
  });

  // Maven
  files.push({
    path: 'pom.xml',
    content: generatePomXml(spec, options),
    language: 'xml',
  });

  // README
  files.push({
    path: 'README.md',
    content: generateReadme(spec, options),
    language: 'markdown',
  });

  return files;
}
